### PR TITLE
Jdbc unittest stubs

### PR DESCRIPTION
**Pull request by eharrow**
This PR retrofits some unit tests to the current code base.  In the case of the early cut of the JDBC code it verifies that UOE are thrown which means that these tests will require refactoring once the actual code is implemented.

### CODE REVIEW

**Review by phughk — APPROVED** [review]
Thanks!

**Comment by phughk** [comment]
I am removing the draft tag. I will give it a day or 2 before landing. But the changes included already are good to land.

**Comment by eharrow** [comment]
Planning to add the same style stub tests for the remaining jdbc classes for the auto generated overrides if you want to hold fire for a few days.

**Review by phughk — COMMENTED** [review]
Looking good so far. Not sure we want the tests to be tied to something that isn't an implementation though. Could equally have the tests skipped with a comment that they need implementing. Otherwise it's good thank you! Holding off for remainder

**Comment by eharrow** [comment]
Yes disabling probably works in this case once the stubs created.  Different strokes… .

**Comment by phughk** [comment]
Already approved, waiting for it to come out of draft before final review and merging. Looks good, thanks!

**Comment by eharrow** [comment]
> Already approved, waiting for it to come out of draft before final review and merging. Looks good, thanks!

Done

**Comment by flipflopsen** [comment]
@phughk Is there already active work on the JDBC Driver implementation?
I started to work on this but facing some problems with this, maybe we can work together on this and interchange information?
In case I am on the official Surreal Discord to find under the name flipflop, otherwise Discord directly: flipflop#1337.

I would really appreciate a message! :)

Sorry for communication over this PR, but I haven't seen another possible way of communicating haha.

**Comment by phughk** [comment]
Heya! Thanks so much for that! Sent a friend request and continuing convo on the surrealdb discord java channel :)

**Pull request merged**
