### PR TITLE
Expanded DB-Driver with methods for 'SignUp', 'Authenticate' and 'Invalidate'.

### PR DESCRIPTION
**Pull request by flipflopsen**
# What I've done
As mentioned in the title I expanded the DB-Driver implementation for the usage of the authenticate via. JWT,- the signup- and the invalidate method.

# Why did I do it?
While looking through the documentation of surreal.js I've noticed that surreal.java is missing some methods which are implemented in the .js version.

### CODE REVIEW

**Comment by phughk** [comment]
Hey @flipflopsen , would you be able to resolve the conflicts with main branch and this PR please?
https://github.com/surrealdb/surrealdb.java/pull/7

**Comment by flipflopsen** [comment]
@phughk thank you for the comment, I nearly forgot about the PR!
I will resolve the conflicts asap. :)

**Comment by phughk** [comment]
Hey @flipflopsen ! Was wondering if you wanted to continue this :) No problem if not, but I will close it in a month or 2 if it isn't resolved. Thank you for the awesome work!

**Comment by phughk** [comment]
Thanks for this! 🎉

**Pull request merged**
